#!/bin/bash

. $(dirname $(realpath $0))/disp

BRANCH=$(git rev-parse --abbrev-ref HEAD) || exit 1

echo -n "confirm: $(disp 33)git push -u origin --force-with-lease $BRANCH$(disp) "
read discard

git push -u origin --force-with-lease $BRANCH
