#!/bin/bash

. $(dirname $(realpath $0))/lib/disp

BRANCH=$(git rev-parse --abbrev-ref HEAD) || exit 1

git status

echo -n "confirm: $(disp 33)git add . && git commit && git push -u origin $BRANCH$(disp) "
read discard

git add .

if [[ -n "$*" ]]
then
   if [[ -x .git/hooks/gitty-commit-msg-transform ]]
   then
      MESSAGE=$(.git/hooks/gitty-commit-msg-transform "$BRANCH" "$*")
   else
      MESSAGE="$*"
   fi

	git commit -m "$MESSAGE"
else
	git commit
fi

git push -u origin $BRANCH

$(dirname $(realpath $0))/lib/github-links $BRANCH
