#!/bin/bash

. $(dirname $(realpath $0))/lib/disp

git rev-parse --abbrev-ref HEAD >/dev/null || exit 1

BRANCH=develop

if [[ ! -z "$1" ]]
then
  BRANCH=$1
fi

echo -n "confirm: $(disp 33)git rebase $BRANCH$(disp) "
read discard

git rebase $BRANCH
