#!/bin/bash

. $(realpath $(dirname $0))/disp

# Extract the origin URI and convert it to a HTTPS URL
REMOTE_URL=$(git remote -v | grep -E '^origin.+push\)$' | awk '{ print $2 }')
REMOTE_URL=$(echo $REMOTE_URL | sed -r 's/^git@([^:]+):(.+)\.git$/https:\/\/\1\/\2/')

if [[ "$REMOTE_URL" = *github.com* ]]
then 
  echo "$(disp 36)$REMOTE_URL/commit/$(git rev-parse HEAD)$(disp)"
  echo "$(disp 36)$REMOTE_URL/compare/$BRANCH?expand=1$(disp)"
fi
